baseURL = "https://qtejojo.github.io/jojo_site/"
languageCode = 'en-us'
title = "JoJo Qi's Site"

# Multi-lingual mode config
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content/en'
  weight = 1

[languages.zh]
  languageName = '中文'
  contentDir = 'content/zh'
  weight = 2

[params]
  # Theme configuration
  BookTheme = 'light'
  # Enable multilingual mode
  BookTranslatedOnly = false
